name: SurvivalCompetition
version: '${project.version}'
main: xiamomc.survivalcompetition.SurvivalCompetition
api-version: 1.19
authors: [ XiaMoDevTeam ]
website: https://www.xiamomc.ink
depend: ['Multiverse-Core', 'Multiverse-Inventories', 'Multiverse-NetherPortals']

commands:
  joinsg:
    usage: '/joinsg'
    description: 'Try to join the game'

  setcareer:
    usage: '/setcareer careers'
    description: 'set ones career'

  game:
    usage: '/game ...'


permissions:
  xiamo.sc.reload:
    description: reload config
    default: false

  xiamo.sc.stopcurrent:
    description: Stop current
    default: false